# SPDX-FileCopyrightText: 2026 Emily <hello@emily.moe>
#
# SPDX-License-Identifier: BlueOak-1.0.0

[graph]
all-features = true

[bans]
multiple-versions-include-dev = true
skip = [
    { crate = "syn@2.0.119", reason = "syn 3.0 is new and hasn’t yet diffused" },
]

[licenses]
allow = ["BlueOak-1.0.0", "ISC", "MIT", "Unicode-3.0"]

[sources]
allow-git = [
    # We need file description passing; see
    # <https://github.com/capnproto/capnproto-rust/pull/666>.
    "https://github.com/emilazy/capnproto-rust.git",
]
